config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   get '/top' => 'homes#top'
   get '/index' => 'posts#index'
   get '/posts/:id' => 'posts#show', as: 'post'
   get '/posts/:id/edit' => 'posts#edit', as: 'edit_post'
   post '/posts' => 'posts#create', as: 'articles'
   patch '/posts/:id/edit' => 'posts#update', as: 'update_post'
   delete '/posts/:id' => 'posts#destroy', as: 'destroy_post'
   root to: 'homes#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, length: { maximum: 20 }
	validates :weather, length: { maximum: 10 }
	validates :body, length: { maximum: 200 }
	attachment :image

	after_create :set_default_img


	def set_default_img
		image_id = "/assets/no_img.png" if !image_id.present?
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  	@post = Article.new
  end

  def index
  	@posts = Article.all
    @post = Article.new
  end

  def show
  	@post = Article.find(params[:id])
  end

  def edit
    @post = Article.find(params[:id])
  end

  def create
    # ストロングパラメーターを使用
     post = Article.new(post_params)
    # DBへ保存する
    if post.save
      # トップ画面へリダイレクト
      redirect_to index_path
    else
      render 'new' #失敗の場合 
    end
  end

  def update
    post = Article.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Article.find(params[:id])
    post.destroy
    redirect_to indexfF_path
  end

	private
		def post_params
	 		params.require(:article).permit(:title, :weather, :body, :image)
	 	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/homes/top.html.erb
<body>


	<div class="profile">
		<table>
			<tr>
				<td>
					<div class="img">
						<%= image_tag 'dog_img_shiba.jpg', :class => "img_dog"%>
					</div>
				</td>
				<td>
					<h1><span>Baba Shunya</span></h1>
				</td>
			</tr>
		</table>
	</div>

	<div class="new">
		<%=link_to '新規投稿', "/posts/new" %>
	</div>
	<div class="toIndex">
		<%=link_to '一覧', "/index" %>
	</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BabaDiary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>編集画面</h1>
<%= form_for(@post, url: edit_post_path) do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
	<h4>天気</h4>
	<%= f.text_field :weather %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <h4>画像</h4>
	<%= f.attachment_field :image %>
    <%= f.submit '保存' %>
<% end %>


<%= link_to "戻る", index_path %>

app/views/posts/index.html.erb
<ul class="nav nav-tabs">
	<li role="presentation" class="active"><a href="#">ホーム</a></li>
	<li role="presentation"><a href="#">メニューＡ</a></li>
	<li role="presentation"><a href="#">メニューＢ</a></li>
</ul>

<h1>投稿一覧</h1>


<div class="toTop">
	<%=link_to 'top', '/top' %>
</div>
<div class="new">
	<%=link_to '新規投稿', "/posts/new" %>
</div>



<h1>新規投稿</h1>


<div class="container-fluid">
	<div class="row">
		<div class="col-md-2">
			<!-- form_for部分 -->
			<%= form_for(@post) do |f| %>

			<h4>タイトル</h4>
			<%= f.text_field :title %>

			<h4>天気</h4>
			<%= f.text_field :weather %>

			<h4>本文</h4>
			<%= f.text_area :body %>

			<%= f.submit '投稿' %>

			<% end %>
		</div>
		<div class="col-md-10">
			<table class="table">
				<th>
					<p>編集</p>
				</th>
				<th>
					<p>削除</p>
				</th>
				<th>
					<p>タイトル</p>
				</th>
				<th>
					<p>天気</p>
				</th>
				<th>
					<p>本文</p>
				</th>
				<th>
					<p>投稿時間</p>
				</th>
				<th>
					<p>画像</p>
				</th>

				<% @posts.each.with_index(1) do |post, i| %>
				<tr>
					<td>
						<%=link_to '[編集]', edit_post_path(post.id) %>
					</td>
					<td>
						<%= link_to "[削除]", destroy_post_path(post.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
					</td>
					<td>
						<span>
							<%=link_to post.title, "/posts/#{post.id}" %>
						</span>
					</td>
					<td>
						<span><%= post.weather %></span>
					</td>
					<td>
						<span><%= post.body %></span>
					</td>
					<td>
						<span><%= post.created_at.strftime('%Y/%m/%d %H:%M') %></span>
					</td>
					<td>
						<% if post.image.present? %>
							<%= attachment_image_tag post, :image, :fill, 100, 100, format: 'jpeg' %>
						<% else %>
							<%= image_tag 'no_img.png', :size => "100x100", :class => "no_img"%>
						<% end %>
					</td>
				</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

<% if @post.errors.any? %>
   <p>エラーでーす。</p>
<% end %>

<h1>新規投稿</h1>
<!-- form_for部分 -->
<%= form_for(@post) do |f| %>

    <h4>タイトル</h4>
    <%= f.text_field :title %>

    <h4>天気</h4>
    <%= f.text_field :weather %>

    <h4>本文</h4>
    <%= f.text_area :body %>

    <h4>画像</h4>
		<%= f.attachment_field :image %>

    <%= f.submit '投稿' %>

<% end %>

<div class="back">
		<%=link_to '戻る', "/index" %>
</div>

app/views/posts/show.html.erb
<h2>タイトル</h2>
<p><%= @post.title %></p>
<h2>天気</h2>
<p><%= @post.weather %></p>
<h2>本文</h2>
<p><%= @post.body %></p>
<h2>画像</h2>
<p><%= attachment_image_tag @post, :image, :fill, 300, 300, format: 'jpeg' %></p>
<%= link_to "編集", edit_post_path(@post.id) %>
<p>投稿時間</p>
  <span><%= @post.created_at.strftime('%Y/%m/%d %H:%M') %></span>

<p><%= link_to "削除", destroy_post_path(@post.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></p>
<div class="back">
		<%=link_to '戻る', '/index' %>
</div>